services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    environment:
      - VK_API_TOKEN=your_vk_token
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    ports:
      - "5000:5000"